CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --mode train \
    --model_type DDIM \
    --img_size 256 \
    --num_img_channels 1 \
    --dataset avt \
    --img_dir data/data \
    --train_batch_size 8 \
    --eval_batch_size 4 \
    --num_epochs 400 \
    --seg_dir data/mask \
    --segmentation_guided \
    --num_segmentation_classes 2 \